In [1]:
# Imports
import pandas as pd

In [2]:
# Read the CSV file and put it into a dataframe

csv_file = 'Resources/original_book_data.csv'
book_df = pd.read_csv(csv_file, na_filter = True, na_values = '[]')
book_df.head()

,bookId,title,series,author,rating,description,language,isbn,genres,characters,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",...,NaN,['Locus Award Nominee for Best Young Adult Boo...,6376780,"['3444695', '1921313', '745221', '171994', '93...",96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...,2993816,30516,5.09
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",...,06/21/03,['Bram Stoker Award for Works for Young Reader...,2507623,"['1593642', '637516', '222366', '39573', '14526']",98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...,2632233,26923,7.38
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,07/11/60,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",4501075,"['2363896', '1333153', '573280', '149952', '80...",95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",...,01/28/13,NaN,2998241,"['1617567', '816659', '373311', '113934', '767...",94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,NaN
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",...,10/05/05,"['Georgia Peach Book Award (2007)', 'Buxtehude...",4964519,"['1751460', '1113682', '1008686', '542017', '5...",78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...,1459448,14874,2.1

Notes: Price is funky and has some blanks

In [5]:
# Store the columns we want in a new DF
book_df2 = book_df[['title', 'author','rating', 'description', 'language', 'isbn',
    'genres', 'pages', 'publishDate', 'publisher', 'numRatings', 'ratingsByStars', 'likedPercent']].copy()

    ## note - price is not included because there were many null values.
    ## we will get the price via web scraping

# Filter DF to only include books in English and drop null values
book_df2 = book_df2[book_df2['language'] == 'English']
book_df2.dropna(inplace = True)

book_df2.head()

,title,author,rating,description,language,isbn,genres,pages,publishDate,publisher,numRatings,ratingsByStars,likedPercent
0,The Hunger Games,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,09/14/08,Scholastic Press,6376780,"['3444695', '1921313', '745221', '171994', '93...",96.0
1,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,09/28/04,Scholastic Inc.,2507623,"['1593642', '637516', '222366', '39573', '14526']",98.0
2,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...",324,05/23/06,Harper Perennial Modern Classics,4501075,"['2363896', '1333153', '573280', '149952', '80...",95.0
3,Pride and Prejudice,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"['Classics', 'Fiction', 'Romance', 'Historical...",279,10/10/00,Modern Library,2998241,"['1617567', '816659', '373311', '113934', '767...",94.0
4,Twilight,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,09/06/06,"Little, Brown and Company",4964519,"['1751460', '1113682', '1008686', '542017', '5...",78.0

In [6]:
# Determine the column dtypes
book_df2.dtypes

title              object
author             object
rating            float64
description        object
language           object
isbn               object
genres             object
pages              object
publishDate        object
publisher          object
numRatings          int64
ratingsByStars     object
likedPercent      float64
dtype: object

In [7]:
## convert the Title, Author, Language column to a string
book_df2['title'] = book_df2['title'].astype('string')
book_df2['author'] = book_df2['author'].astype('string')
book_df2['language'] = book_df2['language'].astype('string')


# first convert pages to a string
book_df2['pages'] = book_df2['pages'].astype('string')
## then remove '1 page' values
book_df2.drop(book_df2[book_df2['pages'] == '1 page'].index, inplace = True)
## convert the pages to an integer
#book_df2['pages'] = book_df2['pages'].astype('int64')
book_df2['pages'].unique()

<StringArray>
[ '374',  '870',  '324',  '279',  '501',  '552',  '141',  '767', '1728',
 '1037',
 ...
 '1507',  '941', '1612', '1115', '2592', '1352', '1020', '2306',  '621',
 '1613']
Length: 1240, dtype: string

HELP ABOVE --- It wont let me convert the pages to an integer... maybe skip if we aren't using it in analysis?

In [8]:
## convert the ISBN column to a string
book_df2['isbn'] = book_df2['isbn'].astype('string')

# drop books with the ISBN of 9999999999999
book_df2.drop(book_df2[book_df2['isbn'] == '9999999999999'].index, inplace = True)

# remove duplicate ISBN numbers
book_df2.drop_duplicates(subset=['isbn'], keep = 'first')

book_df2.head()

,title,author,rating,description,language,isbn,genres,pages,publishDate,publisher,numRatings,ratingsByStars,likedPercent
0,The Hunger Games,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,09/14/08,Scholastic Press,6376780,"['3444695', '1921313', '745221', '171994', '93...",96.0
1,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,09/28/04,Scholastic Inc.,2507623,"['1593642', '637516', '222366', '39573', '14526']",98.0
4,Twilight,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,09/06/06,"Little, Brown and Company",4964519,"['1751460', '1113682', '1008686', '542017', '5...",78.0
5,The Book Thief,Markus Zusak (Goodreads Author),4.37,Librarian's note: An alternate cover edition c...,English,9780375831003,"['Historical Fiction', 'Fiction', 'Young Adult...",552,03/14/06,Alfred A. Knopf,1834276,"['1048230', '524674', '186297', '48864', '26211']",96.0
6,Animal Farm,"George Orwell, Russell Baker (Preface), C.M. W...",3.95,Librarian's note: There is an Alternate Cover ...,English,9780451526342,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",141,04/28/96,Signet Classics,2740713,"['986764', '958699', '545475', '165093', '84682']",91.0

In [9]:

# export to csv to share with the team

book_df2.to_csv('clean_book_data_1.csv', index=False)

In [10]:

'''

Thoughts
There are 33,000+ items with a price and 6,700 without a price.
Do you think it would be easier if we remove the price from this
DF and scrape amazon for the isbn and price so it's consistant
and then we wouldnt scrape for author data (unless that's already complete)


Null values
    some generes are empty lists (2434)
    page numbers not listed (950), page number less than 5 (135)
    blank publisher (1735)
    Empty list for ratings (725) -- maybe we can remove any book with
       fewer than 100 ratings (4842, we'd be left with 35,414 books)


Cleaning up the Author name 
Would it be easier to scrape if we remove anything after a comma so we only have one author listed?

- Additional text we'd need to remove
    Other funky terms
        (Goodreads Author)
        (Illustrator)
        (Translator, Introduction)
        (Translator)
        (Editor)
        (Foreword)
        (Pseudonym)
        (Editor/Contributor)
        non-alphabet characters like Ø¹Ù„Ø§Ø¡ Ø§Ù„Ø£Ø³ÙˆØ§Ù†ÙŠÃ©Ã‰
            this could also remove periods, which we might want to keep


'''

"\n\nThoughts\nThere are 33,000+ items with a price and 6,700 without a price.\nDo you think it would be easier if we remove the price from this\nDF and scrape amazon for the isbn and price so it's consistant\nand then we wouldnt scrape for author data (unless that's already complete)\n\n\nNull values\n    some generes are empty lists (2434)\n    page numbers not listed (950), page number less than 5 (135)\n    blank publisher (1735)\n    Empty list for ratings (725) -- maybe we can remove any book with\n       fewer than 100 ratings (4842, we'd be left with 35,414 books)\n\n\nCleaning up the Author name \nWould it be easier to scrape if we remove anything after a comma so we only have one author listed?\n\n- Additional text we'd need to remove\n    Other funky terms\n        (Goodreads Author)\n        (Illustrator)\n        (Translator, Introduction)\n        (Translator)\n        (Editor)\n        (Foreword)\n        (Pseudonym)\n        (Editor/Contributor)\n        non-alphabet characters like Ø¹Ù„Ø§Ø¡ Ø§Ù„Ø£Ø³ÙˆØ§Ù†ÙŠÃ©Ã‰\n            this could also remove periods, which we might want to keep\n\n\n"