In [11]:
# Imports
import pandas as pd

In [12]:
# Read the CSV file and put it into a dataframe

csv_file = 'Resources/original_book_data.csv'
book_df = pd.read_csv(csv_file, na_filter = True, na_values = '[]')
book_df.head()

,bookId,title,series,author,rating,description,language,isbn,genres,characters,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",...,NaN,['Locus Award Nominee for Best Young Adult Boo...,6376780,"['3444695', '1921313', '745221', '171994', '93...",96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...,2993816,30516,5.09
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",...,06/21/03,['Bram Stoker Award for Works for Young Reader...,2507623,"['1593642', '637516', '222366', '39573', '14526']",98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...,2632233,26923,7.38
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,07/11/60,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",4501075,"['2363896', '1333153', '573280', '149952', '80...",95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",...,01/28/13,NaN,2998241,"['1617567', '816659', '373311', '113934', '767...",94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,NaN
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",...,10/05/05,"['Georgia Peach Book Award (2007)', 'Buxtehude...",4964519,"['1751460', '1113682', '1008686', '542017', '5...",78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...,1459448,14874,2.1

Notes: Price is funky and has some blanks

In [25]:
# Store the columns we want in a new DF
book_df2 = book_df[['title', 'author','rating', 'description', 'language', 'isbn',
    'genres', 'pages', 'publishDate', 'publisher', 'numRatings', 'likedPercent','awards','price']].copy()

    ## note - price is not included because there were many null values.
    ## we will get the price via web scraping

# Filter DF to only include books in English and drop null values
book_df2 = book_df2[book_df2['language'] == 'English']
book_df2.dropna(inplace = True)

book_df2.head()

,title,author,rating,description,language,isbn,genres,pages,publishDate,publisher,numRatings,likedPercent,awards,price
0,The Hunger Games,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,09/14/08,Scholastic Press,6376780,96.0,['Locus Award Nominee for Best Young Adult Boo...,5.09
1,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,09/28/04,Scholastic Inc.,2507623,98.0,['Bram Stoker Award for Works for Young Reader...,7.38
4,Twilight,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,09/06/06,"Little, Brown and Company",4964519,78.0,"['Georgia Peach Book Award (2007)', 'Buxtehude...",2.1
5,The Book Thief,Markus Zusak (Goodreads Author),4.37,Librarian's note: An alternate cover edition c...,English,9780375831003,"['Historical Fiction', 'Fiction', 'Young Adult...",552,03/14/06,Alfred A. Knopf,1834276,96.0,['National Jewish Book Award for Children’s an...,3.8
6,Animal Farm,"George Orwell, Russell Baker (Preface), C.M. W...",3.95,Librarian's note: There is an Alternate Cover ...,English,9780451526342,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",141,04/28/96,Signet Classics,2740713,91.0,"['Prometheus Hall of Fame Award (2011)', 'Retr...",4.42

In [26]:
# Determine the column dtypes
book_df2.dtypes

title            object
author           object
rating          float64
description      object
language         object
isbn             object
genres           object
pages            object
publishDate      object
publisher        object
numRatings        int64
likedPercent    float64
awards           object
price            object
dtype: object

In [28]:
## convert the Title, Author, Language column to a string
book_df2['title'] = book_df2['title'].astype('string')
book_df2['author'] = book_df2['author'].astype('string')
book_df2['language'] = book_df2['language'].astype('string')
book_df2['price'] = book_df2['price'].astype('float')
book_df2.dtypes

title            string
author           string
rating          float64
description      object
language         string
isbn             object
genres           object
pages            object
publishDate      object
publisher        object
numRatings        int64
likedPercent    float64
awards           object
price           float64
dtype: object

In [29]:
## convert the ISBN column to a string
book_df2['isbn'] = book_df2['isbn'].astype('string')

# drop books with the ISBN of 9999999999999
book_df2.drop(book_df2[book_df2['isbn'] == '9999999999999'].index, inplace = True)

# remove duplicate ISBN numbers
book_df2.drop_duplicates(subset=['isbn'], keep = 'first')

book_df2.head()

,title,author,rating,description,language,isbn,genres,pages,publishDate,publisher,numRatings,likedPercent,awards,price
0,The Hunger Games,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,09/14/08,Scholastic Press,6376780,96.0,['Locus Award Nominee for Best Young Adult Boo...,5.09
1,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,09/28/04,Scholastic Inc.,2507623,98.0,['Bram Stoker Award for Works for Young Reader...,7.38
4,Twilight,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,09/06/06,"Little, Brown and Company",4964519,78.0,"['Georgia Peach Book Award (2007)', 'Buxtehude...",2.10
5,The Book Thief,Markus Zusak (Goodreads Author),4.37,Librarian's note: An alternate cover edition c...,English,9780375831003,"['Historical Fiction', 'Fiction', 'Young Adult...",552,03/14/06,Alfred A. Knopf,1834276,96.0,['National Jewish Book Award for Children’s an...,3.80
6,Animal Farm,"George Orwell, Russell Baker (Preface), C.M. W...",3.95,Librarian's note: There is an Alternate Cover ...,English,9780451526342,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",141,04/28/96,Signet Classics,2740713,91.0,"['Prometheus Hall of Fame Award (2011)', 'Retr...",4.42

In [30]:
test_df = book_df2[['author', 'isbn']].copy()
test_df = test_df.set_index('isbn')
test_df.head(12)

                                                          author
isbn
9780439023481                                    Suzanne Collins
9780439358071          J.K. Rowling, Mary GrandPré (Illustrator)
9780316015844                                    Stephenie Meyer
9780375831003                    Markus Zusak (Goodreads Author)
9780451526342  George Orwell, Russell Baker (Preface), C.M. W...
9780446675536                                  Margaret Mitchell
9780062024039                   Veronica Roth (Goodreads Author)
9780062315007  Paulo Coelho (Goodreads Author), Alan R. Clark...
9781416914280                 Cassandra Clare (Goodreads Author)
9780812550702  Orson Scott Card, Stefan Rudnicki (Narrator), ...
9780064410939  E.B. White, Garth Williams (Illustrator), Rose...
9780142000670                                     John Steinbeck

In [32]:
# Split the Author Strings by a comma

new_df = pd.DataFrame(test_df['author'].str.split(pat=',', n=-1, expand=True))
new_df

,0,1,2,3,4,5,6,7,8,9
isbn,,,,,,,,,,
9780439023481,Suzanne Collins,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
9780439358071,J.K. Rowling,Mary GrandPré (Illustrator),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
9780316015844,Stephenie Meyer,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
9780375831003,Markus Zusak (Goodreads Author),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
9780451526342,George Orwell,Russell Baker (Preface),C.M. Woodhouse (Introduction),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...
9780316200639,Peter Brown,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
9781760111236,Charlotte Wood,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
9781111493820,C.J. Cherryh (Goodreads Author),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
9781414348643,DiAnn Mills (Goodreads Author),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
9781461017097,Kim Richardson (Goodreads Author),<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [33]:
# Keep only the index and column of the first author
author_table = new_df.loc[:, :0]

#name the author column 
author_table.columns = ['author']

author_table

                                          author
isbn
9780439023481                    Suzanne Collins
9780439358071                       J.K. Rowling
9780316015844                    Stephenie Meyer
9780375831003    Markus Zusak (Goodreads Author)
9780451526342                      George Orwell
...                                          ...
9780316200639                        Peter Brown
9781760111236                     Charlotte Wood
9781111493820    C.J. Cherryh (Goodreads Author)
9781414348643     DiAnn Mills (Goodreads Author)
9781461017097  Kim Richardson (Goodreads Author)

[8449 rows x 1 columns]

In [34]:
# Keep only the authors name
split_author = pd.DataFrame(author_table['author'].str.split(pat='(', n=-1, expand=True))
split_author

                             0                  1     2
isbn
9780439023481  Suzanne Collins               <NA>  <NA>
9780439358071     J.K. Rowling               <NA>  <NA>
9780316015844  Stephenie Meyer               <NA>  <NA>
9780375831003    Markus Zusak   Goodreads Author)  <NA>
9780451526342    George Orwell               <NA>  <NA>
...                        ...                ...   ...
9780316200639      Peter Brown               <NA>  <NA>
9781760111236   Charlotte Wood               <NA>  <NA>
9781111493820    C.J. Cherryh   Goodreads Author)  <NA>
9781414348643     DiAnn Mills   Goodreads Author)  <NA>
9781461017097  Kim Richardson   Goodreads Author)  <NA>

[8449 rows x 3 columns]

In [35]:
# Keep only the index and column of the first author
author_df = split_author.loc[:, :0]

#name the author column 
author_df.columns = ['main author']

#rename the index
author_df = author_df.rename(index = {'' : 'isbn'})

author_df

                   main author
isbn
9780439023481  Suzanne Collins
9780439358071     J.K. Rowling
9780316015844  Stephenie Meyer
9780375831003    Markus Zusak
9780451526342    George Orwell
...                        ...
9780316200639      Peter Brown
9781760111236   Charlotte Wood
9781111493820    C.J. Cherryh
9781414348643     DiAnn Mills
9781461017097  Kim Richardson

[8449 rows x 1 columns]

In [36]:
# export to csv to share with the team

author_df.to_csv('author_table.csv', index=True)

In [37]:
# merge data from the author table to the main data

main_book_data = pd.merge(book_df2, author_df, on = 'isbn')

#remove the original author column
main_book_data = main_book_data.drop(columns=['author'])

main_book_data

,title,rating,description,language,isbn,genres,pages,publishDate,publisher,numRatings,likedPercent,awards,price,main author
0,The Hunger Games,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,09/14/08,Scholastic Press,6376780,96.0,['Locus Award Nominee for Best Young Adult Boo...,5.09,Suzanne Collins
1,Harry Potter and the Order of the Phoenix,4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,09/28/04,Scholastic Inc.,2507623,98.0,['Bram Stoker Award for Works for Young Reader...,7.38,J.K. Rowling
2,Twilight,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,09/06/06,"Little, Brown and Company",4964519,78.0,"['Georgia Peach Book Award (2007)', 'Buxtehude...",2.10,Stephenie Meyer
3,The Book Thief,4.37,Librarian's note: An alternate cover edition c...,English,9780375831003,"['Historical Fiction', 'Fiction', 'Young Adult...",552,03/14/06,Alfred A. Knopf,1834276,96.0,['National Jewish Book Award for Children’s an...,3.80,Markus Zusak
4,Animal Farm,3.95,Librarian's note: There is an Alternate Cover ...,English,9780451526342,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",141,04/28/96,Signet Classics,2740713,91.0,"['Prometheus Hall of Fame Award (2011)', 'Retr...",4.42,George Orwell
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8460,Mr. Tiger Goes Wild,4.18,Are you bored with being so proper?\nDo you wa...,English,9780316200639,"['Picture Books', 'Childrens', 'Animals', 'Sto...",40,September 3rd 2013,"Little, Brown & Company",7032,96.0,"[""Vermont's Picture Book Awards: Red Clover No...",5.20,Peter Brown
8461,The Natural Way of Things,3.53,Two women awaken from a drugged sleep to find ...,English,9781760111236,"['Fiction', 'Dystopia', 'Australia', 'Feminism...",320,October 1st 2015,Allen & Unwin,10894,84.0,['Miles Franklin Literary Award Nominee for Li...,10.37,Charlotte Wood
8462,Arafel's Saga,3.69,"Journey to a transitional time in the world, a...",English,9781111493820,"['Fantasy', 'Fiction', 'Science Fiction Fantas...",408,January 1st 1983,"Nelson Doubleday, Inc.",1070,87.0,['World Fantasy Award Nominee for Best Novella...,5.18,C.J. Cherryh
8463,Attracted to Fire,4.14,Special Agent Meghan Connors' dream of one day...,English,9781414348643,"['Christian Fiction', 'Christian', 'Suspense',...",416,October 1st 2011,Tyndale House Publishers,2143,95.0,['HOLT Medallion by Virginia Romance Writers N...,5.55,DiAnn Mills
8464,Marked,3.70,--READERS FAVORITE AWARDS WINNER 2011--Sixteen...,English,9781461017097,"['Fantasy', 'Young Adult', 'Paranormal', 'Ange...",280,March 18th 2011,CreateSpace,6674,84.0,"[""Readers' Favorite Book Award (2011)""]",7.37,Kim Richardson

In [24]:
# Export to CSV file
main_book_data.to_csv('main_table.csv', index=True)